export type ReportType =
  | 'test_execution'
  | 'bug_summary'
  | 'performance'
  | 'regression'
  | 'release_readiness';

export type ExportFormat = 'excel';

export type ReportFrequency = 'daily' | 'weekly' | 'monthly';

export interface ReportFilters {
  dateFrom?: string;
  dateTo?: string;
  project?: string;
  environment?: string;
  severity?: string;
}

export interface StoredReport {
  id: string;
  name: string;
  type: ReportType;
  format: ExportFormat;
  filters: ReportFilters;
  createdAt: string;
  size: number;
  sizeFormatted: string;
  shareToken: string;
  status: 'completed' | 'generating' | 'failed';
}

export interface ScheduledReport {
  id: string;
  name: string;
  type: ReportType;
  format: ExportFormat;
  frequency: ReportFrequency;
  dayOfWeek?: number;
  dayOfMonth?: number;
  time: string;
  recipients: string[];
  filters: ReportFilters;
  active: boolean;
  createdAt: string;
  lastSentAt?: string;
  nextRunAt?: string;
}

export interface BrandingSettings {
  companyName: string;
  primaryColor: string;
  secondaryColor: string;
  logoUrl?: string;
  footerText?: string;
}

export const DEFAULT_BRANDING: BrandingSettings = {
  companyName: 'QA360',
  primaryColor: '#2563eb',
  secondaryColor: '#64748b',
  footerText: 'Generated by QA360 Test Management Platform',
};
