// Report system types for QA360 Enterprise Reporting

export type ReportType =
  | 'test_execution'
  | 'bug_summary'
  | 'performance'
  | 'regression'
  | 'release_readiness';

export type ExportFormat = 'pdf' | 'csv' | 'excel';

export type ReportFrequency = 'daily' | 'weekly' | 'monthly';

export interface ReportFilters {
  dateFrom?: string;
  dateTo?: string;
  project?: string;
  environment?: string;
  severity?: string;
}

export interface StoredReport {
  id: string;
  name: string;
  type: ReportType;
  format: ExportFormat;
  filters: ReportFilters;
  createdAt: string;
  size: number;
  sizeFormatted: string;
  shareToken: string;
  status: 'completed' | 'generating' | 'failed';
  buffer?: Buffer;
}

export interface ScheduledReport {
  id: string;
  name: string;
  type: ReportType;
  format: ExportFormat;
  frequency: ReportFrequency;
  dayOfWeek?: number;
  dayOfMonth?: number;
  time: string;
  recipients: string[];
  filters: ReportFilters;
  active: boolean;
  createdAt: string;
  lastSentAt?: string;
  nextRunAt?: string;
}

export interface ReportMetric {
  label: string;
  value: string | number;
  change?: number;
  trend?: 'up' | 'down' | 'flat';
}

export interface BrandingSettings {
  companyName: string;
  primaryColor: string;
  logoText: string;
  watermark: string;
  showWatermark: boolean;
  footerText: string;
}

export const DEFAULT_BRANDING: BrandingSettings = {
  companyName: 'QA360',
  primaryColor: '#2563eb',
  logoText: 'QA360',
  watermark: 'CONFIDENTIAL',
  showWatermark: true,
  footerText: 'Generated by QA360 — Enterprise Test Management Platform',
};
