// Playwright Code Generator Service
// Converts recorded actions into Playwright JS/TS/Python scripts

import type { RecordedAction, CodeLanguage, ActionType } from '@/types/codegen';

// ─── Main entry ──────────────────────────────────────────────────────────────

export function generateCode(
  actions: RecordedAction[],
  language: CodeLanguage,
  targetUrl: string,
): string {
  switch (language) {
    case 'playwright-js':
      return generateJS(actions, targetUrl);
    case 'playwright-ts':
      return generateTS(actions, targetUrl);
    case 'python':
      return generatePython(actions, targetUrl);
  }
}

// ─── JavaScript ──────────────────────────────────────────────────────────────

function generateJS(actions: RecordedAction[], targetUrl: string): string {
  const needsExpect = actions.some((a) => isAssertion(a.type));
  const lines: string[] = [
    `// Generated by QA360 Code Generator`,
    `// Target: ${targetUrl}`,
    ``,
    `const { test, expect } = require('@playwright/test');`,
    ``,
    `test('recorded test', async ({ page }) => {`,
    `  await page.goto('${targetUrl}');`,
    ``,
  ];

  for (const action of actions) {
    if (action.description) {
      lines.push(`  // ${action.description}`);
    }
    const line = actionToJS(action);
    if (line) lines.push(line);
    lines.push('');
  }

  lines.push(`});`);
  return lines.join('\n');
}

// ─── TypeScript ───────────────────────────────────────────────────────────────

function generateTS(actions: RecordedAction[], targetUrl: string): string {
  const lines: string[] = [
    `// Generated by QA360 Code Generator`,
    `// Target: ${targetUrl}`,
    ``,
    `import { test, expect } from '@playwright/test';`,
    ``,
    `test('recorded test', async ({ page }) => {`,
    `  await page.goto('${targetUrl}');`,
    ``,
  ];

  for (const action of actions) {
    if (action.description) {
      lines.push(`  // ${action.description}`);
    }
    const line = actionToJS(action); // TS syntax identical to JS for Playwright
    if (line) lines.push(line);
    lines.push('');
  }

  lines.push(`});`);
  return lines.join('\n');
}

// ─── Python ──────────────────────────────────────────────────────────────────

function generatePython(actions: RecordedAction[], targetUrl: string): string {
  const needsExpect = actions.some((a) => isAssertion(a.type));
  const lines: string[] = [
    `# Generated by QA360 Code Generator`,
    `# Target: ${targetUrl}`,
    ``,
    `import pytest`,
    needsExpect ? `from playwright.sync_api import Page, expect` : `from playwright.sync_api import Page`,
    ``,
    ``,
    `def test_recorded(page: Page) -> None:`,
    `    page.goto("${targetUrl}")`,
    ``,
  ];

  for (const action of actions) {
    if (action.description) {
      lines.push(`    # ${action.description}`);
    }
    const line = actionToPython(action);
    if (line) lines.push(line);
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Action converters (JS/TS) ────────────────────────────────────────────────

function actionToJS(action: RecordedAction): string {
  const sel = action.selector || '';
  const val = action.value || '';

  switch (action.type) {
    case 'navigate':
      return `  await page.goto('${val}');`;
    case 'click':
      return `  await ${sel}.click();`;
    case 'fill':
      return `  await ${sel}.fill('${escJS(val)}');`;
    case 'select':
      return `  await ${sel}.selectOption('${escJS(val)}');`;
    case 'check':
      return `  await ${sel}.check();`;
    case 'uncheck':
      return `  await ${sel}.uncheck();`;
    case 'hover':
      return `  await ${sel}.hover();`;
    case 'press':
      return `  await ${sel}.press('${val || 'Enter'}');`;
    case 'assertText':
      return `  await expect(${sel}).toHaveText('${escJS(val)}');`;
    case 'assertVisible':
      return `  await expect(${sel}).toBeVisible();`;
    case 'assertURL':
      return `  await expect(page).toHaveURL('${val}');`;
    case 'screenshot':
      return `  await page.screenshot({ path: '${val || 'screenshot.png'}' });`;
    case 'wait':
      return `  await page.waitForTimeout(${val || '1000'});`;
    default:
      return `  // TODO: ${action.type}`;
  }
}

// ─── Action converters (Python) ───────────────────────────────────────────────

function actionToPython(action: RecordedAction): string {
  const sel = jsToPythonSelector(action.selector || '');
  const val = action.value || '';

  switch (action.type) {
    case 'navigate':
      return `    page.goto("${val}")`;
    case 'click':
      return `    ${sel}.click()`;
    case 'fill':
      return `    ${sel}.fill("${escPy(val)}")`;
    case 'select':
      return `    ${sel}.select_option("${escPy(val)}")`;
    case 'check':
      return `    ${sel}.check()`;
    case 'uncheck':
      return `    ${sel}.uncheck()`;
    case 'hover':
      return `    ${sel}.hover()`;
    case 'press':
      return `    ${sel}.press("${val || 'Enter'}")`;
    case 'assertText':
      return `    expect(${sel}).to_have_text("${escPy(val)}")`;
    case 'assertVisible':
      return `    expect(${sel}).to_be_visible()`;
    case 'assertURL':
      return `    expect(page).to_have_url("${val}")`;
    case 'screenshot':
      return `    page.screenshot(path="${val || 'screenshot.png'}")`;
    case 'wait':
      return `    page.wait_for_timeout(${val || '1000'})`;
    default:
      return `    # TODO: ${action.type}`;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function jsToPythonSelector(js: string): string {
  return js
    .replace(/^page\.getByRole\(/, 'page.get_by_role(')
    .replace(/^page\.getByLabel\(/, 'page.get_by_label(')
    .replace(/^page\.getByPlaceholder\(/, 'page.get_by_placeholder(')
    .replace(/^page\.getByText\(/, 'page.get_by_text(')
    .replace(/^page\.getByTestId\(/, 'page.get_by_test_id(')
    .replace(/^page\.locator\(/, 'page.locator(');
}

function isAssertion(type: ActionType): boolean {
  return type.startsWith('assert');
}

function escJS(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escPy(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

// ─── File extension helper ────────────────────────────────────────────────────

export function getFileExtension(language: CodeLanguage): string {
  switch (language) {
    case 'playwright-js':
      return 'spec.js';
    case 'playwright-ts':
      return 'spec.ts';
    case 'python':
      return 'test_recorded.py';
  }
}

export function getMonacoLanguage(language: CodeLanguage): string {
  return language === 'python' ? 'python' : 'typescript';
}
