pipeline {
    agent any

    tools {
        nodejs 'NodeJS 20'
    }

    stages {

        stage('Install Frontend Dependencies') {
            steps {
                dir('dashboard') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Backend Dependencies') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                dir('backend') {
                    sh 'npx playwright install --with-deps'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('backend') {
                    sh 'npm test'
                }
            }
        }

        stage('Build Frontend') {
            steps {
                dir('dashboard') {
                    sh 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}