import type { RecordedAction, CodeLanguage, ActionType } from '@/types/codegen';

export function generateCode(actions: RecordedAction[], language: CodeLanguage, targetUrl: string): string {
  switch (language) {
    case 'playwright-js': return generateJS(actions, targetUrl);
    case 'playwright-ts': return generateTS(actions, targetUrl);
    case 'python': return generatePython(actions, targetUrl);
  }
}

function isAssertion(type: ActionType) {
  return ['assertText', 'assertVisible', 'assertURL'].includes(type);
}

function actionToJS(action: RecordedAction): string {
  const sel = action.selector ? `page.locator('${action.selector}')` : 'page';
  switch (action.type) {
    case 'navigate': return `  await page.goto('${action.value}');`;
    case 'click': return `  await ${sel}.click();`;
    case 'fill': return `  await ${sel}.fill('${action.value || ''}');`;
    case 'select': return `  await ${sel}.selectOption('${action.value || ''}');`;
    case 'check': return `  await ${sel}.check();`;
    case 'uncheck': return `  await ${sel}.uncheck();`;
    case 'hover': return `  await ${sel}.hover();`;
    case 'press': return `  await ${sel}.press('${action.value || ''}');`;
    case 'assertText': return `  await expect(${sel}).toHaveText('${action.value || ''}');`;
    case 'assertVisible': return `  await expect(${sel}).toBeVisible();`;
    case 'assertURL': return `  await expect(page).toHaveURL('${action.value || ''}');`;
    case 'screenshot': return `  await page.screenshot({ path: 'screenshot.png' });`;
    case 'wait': return `  await page.waitForTimeout(${action.value || '1000'});`;
    default: return '';
  }
}

function actionToPython(action: RecordedAction): string {
  const sel = action.selector ? `page.locator("${action.selector}")` : 'page';
  switch (action.type) {
    case 'navigate': return `    page.goto("${action.value}")`;
    case 'click': return `    ${sel}.click()`;
    case 'fill': return `    ${sel}.fill("${action.value || ''}")`;
    case 'select': return `    ${sel}.select_option("${action.value || ''}")`;
    case 'check': return `    ${sel}.check()`;
    case 'uncheck': return `    ${sel}.uncheck()`;
    case 'hover': return `    ${sel}.hover()`;
    case 'press': return `    ${sel}.press("${action.value || ''}")`;
    case 'assertText': return `    expect(${sel}).to_have_text("${action.value || ''}")`;
    case 'assertVisible': return `    expect(${sel}).to_be_visible()`;
    case 'assertURL': return `    expect(page).to_have_url("${action.value || ''}")`;
    case 'screenshot': return `    page.screenshot(path="screenshot.png")`;
    case 'wait': return `    page.wait_for_timeout(${action.value || 1000})`;
    default: return '';
  }
}

function generateJS(actions: RecordedAction[], targetUrl: string): string {
  return [
    `// Generated by QA360 Code Generator`,
    `// Target: ${targetUrl}`,
    ``,
    `const { test, expect } = require('@playwright/test');`,
    ``,
    `test('recorded test', async ({ page }) => {`,
    `  await page.goto('${targetUrl}');`,
    ``,
    ...actions.flatMap((a) => {
      const lines = [];
      if (a.description) lines.push(`  // ${a.description}`);
      const line = actionToJS(a);
      if (line) lines.push(line);
      lines.push('');
      return lines;
    }),
    `});`,
  ].join('\n');
}

function generateTS(actions: RecordedAction[], targetUrl: string): string {
  return [
    `// Generated by QA360 Code Generator`,
    `// Target: ${targetUrl}`,
    ``,
    `import { test, expect } from '@playwright/test';`,
    ``,
    `test('recorded test', async ({ page }) => {`,
    `  await page.goto('${targetUrl}');`,
    ``,
    ...actions.flatMap((a) => {
      const lines = [];
      if (a.description) lines.push(`  // ${a.description}`);
      const line = actionToJS(a);
      if (line) lines.push(line);
      lines.push('');
      return lines;
    }),
    `});`,
  ].join('\n');
}

function generatePython(actions: RecordedAction[], targetUrl: string): string {
  return [
    `# Generated by QA360 Code Generator`,
    `# Target: ${targetUrl}`,
    ``,
    `import pytest`,
    `from playwright.sync_api import Page, expect`,
    ``,
    `def test_recorded(page: Page):`,
    `    page.goto("${targetUrl}")`,
    ``,
    ...actions.flatMap((a) => {
      const lines = [];
      if (a.description) lines.push(`    # ${a.description}`);
      const line = actionToPython(a);
      if (line) lines.push(line);
      lines.push('');
      return lines;
    }),
  ].join('\n');
}

export function getFileExtension(language: CodeLanguage): string {
  const map: Record<CodeLanguage, string> = {
    'playwright-js': '.js',
    'playwright-ts': '.ts',
    'python': '.py',
  };
  return map[language];
}

export function getMonacoLanguage(language: CodeLanguage): string {
  const map: Record<CodeLanguage, string> = {
    'playwright-js': 'javascript',
    'playwright-ts': 'typescript',
    'python': 'python',
  };
  return map[language];
}
